/* runtime.h — fast-engine C runtime API (design.md §6.17, FR-116a).
 *
 * A design generated by the retrosim editor compiles as two translation
 * units:
 *
 *     cc <design>.c runtime.c
 *
 * runtime.c is fixed and hand-written: it owns main(), the settle/step
 * loops, net resolution, the vector runner, and all reporting. The
 * generated <design>.c is design-specific data plus lowered logic: it
 * implements the gen_* interface declared at the bottom of this file.
 *
 * The runtime re-expresses, bit for bit, the semantics of the editor's
 * slow (debug) simulator (requirements §3.19); FR references below name
 * the requirement each piece mirrors. The two engines must agree on every
 * net's value for any design (FR-107).
 */

#ifndef RETROSIM_RUNTIME_H
#define RETROSIM_RUNTIME_H

/* ------------------------------------------------------------------ *
 *  Four-state signal values (FR-077, FR-107)
 * ------------------------------------------------------------------ */

/* One net value. The numeric codes are identical to the slow simulator's
 * V0/V1/VU/VZ, and one byte per net is the deliberate first-cut encoding
 * (bit-packing is a possible later optimization). */
typedef unsigned char rt_val;

enum {
  RT_0 = 0, /* logic 0 */
  RT_1 = 1, /* logic 1 */
  RT_U = 2, /* undefined */
  RT_Z = 3, /* high impedance (a component reading Z treats it as U) */
};

/* Logical combination, selectively pessimistic as real logic permits
 * (FR-077): an AND with any 0 operand yields 0 and an OR with any 1
 * operand yields 1, regardless of U operands; every other combination
 * involving a U operand yields U. A Z operand reads as U. These are the
 * only combinators the generated evaluate code uses. */
rt_val rt_and(rt_val a, rt_val b);
rt_val rt_or(rt_val a, rt_val b);
rt_val rt_not(rt_val a);
rt_val rt_xor(rt_val a, rt_val b); /* extended-dialect XOR (FR-079a) */

/* rt_buf is the read normalization alone (a non-inverting buffer): Z reads
 * as U, 0/1/U pass through. Generated code applies it to a bare positive
 * literal, where no other combinator would normalize the net value. */
rt_val rt_buf(rt_val a);

/* ------------------------------------------------------------------ *
 *  Net state and the unit step (FR-078, FR-110)
 * ------------------------------------------------------------------ */

/* RT_SETTLE_BOUND is the combinational settling bound in unit steps,
 * matching the slow simulator's (FR-085/FR-115c). */
#define RT_SETTLE_BOUND 10000

/* rt_init allocates the runtime's net and contribution buffers, sets every
 * net to RT_Z (the slow simulator's power-up state), and calls gen_init().
 * Must be called once before any rt_step/rt_settle. Exits with a message
 * on allocation failure. */
void rt_init(void);

/* rt_curr returns the current net-value array (gen_net_count entries),
 * i.e. the values every evaluate function reads. Read-only. */
const rt_val *rt_curr(void);

/* rt_contrib deposits one driver contribution on a net for the step being
 * computed. Called by gen_drive() (and by the runtime's own built-in
 * drivers). A contribution of RT_Z is ignored — a tristate output that is
 * disabled simply does not drive (FR-081). `weak` is nonzero for a
 * pull-up/pull-down (FR-083); `label` indexes gen_labels and names the
 * driver in a bus-conflict report (FR-108). */
void rt_contrib(int net, rt_val v, int weak, int label);

/* rt_step advances one unit (1 simulated ns), double-buffered (FR-078):
 * (1) gen_latch() latches registered/memory state from the previous
 * step's values; (2) gen_drive() plus the runtime's built-in drivers
 * (switches, pulls, scripted clocks/resets) deposit contributions
 * computed from the previous step's values; (3) every net resolves
 * (FR-081–FR-083): enabled strong drivers win, weak drivers decide only
 * when every strong driver is Z, agreeing drivers give their value, a
 * 0-vs-1 disagreement is a bus conflict — the net goes U and the conflict
 * is reported once, on onset, to stderr naming both drivers (FR-108,
 * FR-118) — any deciding U gives U, and no driver at all gives Z;
 * (4) the buffers swap. Returns nonzero if any net changed value. */
int rt_step(void);

/* rt_settle runs rt_step() until quiescence — no net changed — or until
 * RT_SETTLE_BOUND steps have run (FR-085). Returns the number of steps
 * taken to reach quiescence, or -1 if the bound was hit (a likely
 * oscillation; also reported to stderr). */
int rt_settle(void);

/* ------------------------------------------------------------------ *
 *  Vector runner (FR-117, FR-118)
 * ------------------------------------------------------------------ */

/* rt_run_vectors reads test-vector rows from standard input and writes
 * the transcript to standard output. One line per row:
 *
 *     <input symbols> | <expected output symbols>
 *
 * whitespace-separated, positional against gen_incols / gen_outcols
 * (which the generator bakes in the editor's test-vector column order,
 * FR-115b/FR-115f). Input symbols are 0 and 1, plus C (one full positive
 * pulse) in a clock column; expected symbols are H (expect 1), L (expect
 * 0), X (don't-test). Blank lines and lines starting with '#' are
 * skipped.
 *
 * Run semantics mirror the editor's vector runner exactly (FR-117): with
 * no clock generators (gen_clock_count == 0) each row is evaluated
 * independently — drive the inputs, settle, score. With clocks, the rows
 * run in order on persistent state: an implicit power-on-reset preamble
 * first (each reset asserted for its own `cycles` worth of scripted
 * pulses, FR-115e), then per row: apply inputs (C reads as low), settle,
 * pulse all C clocks together (high, settle, low, settle), score.
 * Scoring: H matches 1, L matches 0, X always passes; U and Z match
 * nothing (FR-115c).
 *
 * Transcript (FR-118): one line per row — "row N: pass" or
 * "row N: FAIL <col>=<actual> ..." naming each failing output column and
 * the actual value observed (0/1/U/Z) — then a summary line
 * "passed R of T rows". Returns the number of failing rows (so main()
 * exits 0 iff everything passed). */
int rt_run_vectors(void);

/* ==================================================================== *
 *  The gen_* interface — implemented by the generated <design>.c
 * ==================================================================== */

/* --- Nets and labels --- */

/* Number of nets. Net indices run 0..gen_net_count-1. */
extern const int gen_net_count;

/* Driver/probe name strings, "refdes.pin" (e.g. "U3.Q0"), indexed by the
 * `label` argument of rt_contrib and by the built-in tables below. Used
 * verbatim in bus-conflict reports (FR-108/FR-082). */
extern const char *const gen_labels[];
extern const int gen_label_count;

/* Upper bound on the contributions deposited in any one step (the total
 * driver count: every output-capable pin, built-in driver, and input
 * column). Sizes the runtime's contribution buffer. */
extern const int gen_max_contribs;

/* --- Lowered design logic --- */

/* gen_init resets all generated state to power-up: registers and RAM
 * contents to U (FR-079), ROM contents to their baked bytes (FR-116a),
 * switches to their baked levels. Called once before any step. */
void gen_init(void);

/* gen_latch updates registered state from the previous step's net values
 * (`curr`): .R register latching on each relevant clock's 0→1 edge
 * (FR-079/FR-079a) and memory write ports (FR-114d). Called by rt_step
 * before any contribution is evaluated, so latching sees the pre-step
 * values, exactly like the slow simulator. Empty in a purely
 * combinational design. */
void gen_latch(const rt_val *curr);

/* gen_drive computes every generated strong driver from `curr` and
 * deposits it via rt_contrib: each GALasm output (plain, .T-gated, or
 * registered, FR-079), each memory data pin when its read path is
 * enabled (FR-114d), and each behavior-less type's U-driving output
 * (FR-080). The runtime's own built-in drivers (below) are not gen_drive's
 * concern. */
void gen_drive(const rt_val *curr);

/* --- Built-in instances (behaviors live in runtime.c, FR-116a) --- */

/* Weak pull-up/pull-down (FR-069/FR-070/FR-083). value is RT_1 or RT_0. */
typedef struct {
  int net;
  rt_val value;
  int label;
} rt_pull;
extern const rt_pull gen_pulls[];
extern const int gen_pull_count;

/* Input switch (FR-071c/FR-087a): a strong driver of `level`, its
 * persisted editor state baked at generate time. Mutable: a bound vector
 * input column overwrites `level` row by row. */
typedef struct {
  int net;
  rt_val level;
  int label;
} rt_switch;
extern rt_switch gen_switches[];
extern const int gen_switch_count;

/* Clock generator (FR-071/FR-071a). In vector mode the runner scripts
 * `level` (0/1/C semantics, FR-115e); the free-running mode driven by
 * `period_ns` is a later milestone (design §6.17 M4). gen_clock_count > 0
 * is the sequential/combinational split (FR-086). Mutable: the runner
 * sets `level`. */
typedef struct {
  int net;
  rt_val level;
  int period_ns;
  int label;
} rt_clock;
extern rt_clock gen_clocks[];
extern const int gen_clock_count;

/* Power-on reset (FR-071b): drives R and /R, asserted for `cycles`
 * scripted clock pulses in the vector preamble (FR-115e). Mutable: the
 * runner flips `released`. */
typedef struct {
  int r_net;  /* R  (active high), or -1 when unwired */
  int rn_net; /* /R (active low), or -1 when unwired */
  int cycles;
  int released; /* 0 = asserting reset, 1 = released */
  int r_label;
  int rn_label;
} rt_reset;
extern rt_reset gen_resets[];
extern const int gen_reset_count;

/* Memory devices (RAM/ROM, FR-114): interface lands with milestone M3
 * (design §6.17); until then gen_latch/gen_drive of a memory-bearing
 * design are not generated. */

/* --- Vector columns (FR-117) --- */

/* Input column kinds: what the row symbol drives. */
typedef enum {
  RT_COL_SWITCH, /* ref indexes gen_switches; symbol sets .level */
  RT_COL_CLOCK,  /* ref indexes gen_clocks; symbols 0/1/C (FR-115e) */
  RT_COL_PORT,   /* ref is a net index; symbol strong-drives the net
                  * (the external-stimulus force of FR-115f) */
} rt_col_kind;

typedef struct {
  rt_col_kind kind;
  int ref;
  const char *name;   /* column display label, for the transcript */
  const char *refdes; /* column identity: instance ref (FR-115a, --columns) */
  const char *pin;    /* column identity: pin name (FR-115a, --columns) */
  int label;          /* gen_labels index for the stimulus driver */
} rt_incol;
extern const rt_incol gen_incols[];
extern const int gen_incol_count;

/* Output column: read `net` after settling and score it (FR-115c). */
typedef struct {
  int net;
  const char *name;
  const char *refdes; /* column identity: instance ref (FR-115a, --columns) */
  const char *pin;    /* column identity: pin name (FR-115a, --columns) */
} rt_outcol;
extern const rt_outcol gen_outcols[];
extern const int gen_outcol_count;

#endif /* RETROSIM_RUNTIME_H */
