/* runtime.h — fast-engine C runtime API (design.md §6.17, FR-116a).
 *
 * A design generated by the retrosim editor compiles as two translation
 * units:
 *
 *     cc <design>.c runtime.c
 *
 * runtime.c is fixed and hand-written: it owns main(), the settle/step
 * loops, net resolution, the vector runner, and all reporting. The
 * generated <design>.c is design-specific data plus lowered logic: it
 * implements the gen_* interface declared at the bottom of this file.
 *
 * The runtime re-expresses, bit for bit, the semantics of the editor's
 * slow (debug) simulator (requirements §3.19); FR references below name
 * the requirement each piece mirrors. The two engines must agree on every
 * net's value for any design (FR-107).
 */

#ifndef RETROSIM_RUNTIME_H
#define RETROSIM_RUNTIME_H

/* ------------------------------------------------------------------ *
 *  Four-state signal values (FR-077, FR-107)
 * ------------------------------------------------------------------ */

/* One net value. The numeric codes are identical to the slow simulator's
 * V0/V1/VU/VZ, and one byte per net is the deliberate first-cut encoding
 * (bit-packing is a possible later optimization). */
typedef unsigned char rt_val;

enum {
  RT_0 = 0, /* logic 0 */
  RT_1 = 1, /* logic 1 */
  RT_U = 2, /* undefined */
  RT_Z = 3, /* high impedance (a component reading Z treats it as U) */
};

/* Logical combination, selectively pessimistic as real logic permits
 * (FR-077): an AND with any 0 operand yields 0 and an OR with any 1
 * operand yields 1, regardless of U operands; every other combination
 * involving a U operand yields U. A Z operand reads as U. These are the
 * only combinators the generated evaluate code uses. */
rt_val rt_and(rt_val a, rt_val b);
rt_val rt_or(rt_val a, rt_val b);
rt_val rt_not(rt_val a);
rt_val rt_xor(rt_val a, rt_val b); /* extended-dialect XOR (FR-079a) */

/* rt_buf is the read normalization alone (a non-inverting buffer): Z reads
 * as U, 0/1/U pass through. Generated code applies it to a bare positive
 * literal, where no other combinator would normalize the net value. */
rt_val rt_buf(rt_val a);

/* ------------------------------------------------------------------ *
 *  Net state and the unit step (FR-078, FR-110)
 * ------------------------------------------------------------------ */

/* RT_SETTLE_BOUND is the combinational settling bound in unit steps,
 * matching the slow simulator's (FR-085/FR-115c). */
#define RT_SETTLE_BOUND 10000

/* rt_init allocates the runtime's net and contribution buffers, sets every
 * net to RT_Z (the slow simulator's power-up state), and calls gen_init().
 * Must be called once before any rt_step/rt_settle. Exits with a message
 * on allocation failure. */
void rt_init(void);

/* rt_curr returns the current net-value array (gen_net_count entries),
 * i.e. the values every evaluate function reads. Read-only. */
const rt_val *rt_curr(void);

/* rt_contrib deposits one driver contribution on a net for the step being
 * computed. Called by gen_drive() (and by the runtime's own built-in
 * drivers). A contribution of RT_Z is ignored — a tristate output that is
 * disabled simply does not drive (FR-081). `weak` is nonzero for a
 * pull-up/pull-down (FR-083); `label` indexes gen_labels and names the
 * driver in a bus-conflict report (FR-108). */
void rt_contrib(int net, rt_val v, int weak, int label);

/* rt_step advances one unit (1 simulated ns), double-buffered (FR-078):
 * (1) gen_latch() latches registered/memory state from the previous
 * step's values; (2) gen_drive() plus the runtime's built-in drivers
 * (switches, pulls, scripted clocks/resets) deposit contributions
 * computed from the previous step's values; (3) every net resolves
 * (FR-081–FR-083): enabled strong drivers win, weak drivers decide only
 * when every strong driver is Z, agreeing drivers give their value, a
 * 0-vs-1 disagreement is a bus conflict — the net goes U and the conflict
 * is reported once, on onset, to stderr naming both drivers (FR-108,
 * FR-118) — any deciding U gives U, and no driver at all gives Z;
 * (4) the buffers swap. Returns nonzero if any net changed value. */
int rt_step(void);

/* rt_settle runs rt_step() until quiescence — no net changed — or until
 * RT_SETTLE_BOUND steps have run (FR-085). Returns the number of steps
 * taken to reach quiescence, or -1 if the bound was hit (a likely
 * oscillation; also reported to stderr). */
int rt_settle(void);

/* ------------------------------------------------------------------ *
 *  Vector runner (FR-117, FR-118)
 * ------------------------------------------------------------------ */

/* rt_run_vectors reads test-vector rows from standard input and writes
 * the transcript to standard output. One line per row:
 *
 *     <input symbols> | <expected output symbols>
 *
 * whitespace-separated, positional against gen_incols / gen_outcols
 * (which the generator bakes in the editor's test-vector column order,
 * FR-115b/FR-115f). Input symbols are 0 and 1, plus C (one full positive
 * pulse) in a clock column; expected symbols are H (expect 1), L (expect
 * 0), X (don't-test). Blank lines and lines starting with '#' are
 * skipped.
 *
 * Run semantics mirror the editor's vector runner exactly (FR-117): with
 * no clock generators (gen_clock_count == 0) each row is evaluated
 * independently — drive the inputs, settle, score. With clocks, the rows
 * run in order on persistent state: an implicit power-on-reset preamble
 * first (each reset asserted for its own `cycles` worth of scripted
 * pulses, FR-115e), then per row: apply inputs (C reads as low), settle,
 * pulse all C clocks together (high, settle, low, settle), score.
 * Scoring: H matches 1, L matches 0, X always passes; U and Z match
 * nothing (FR-115c).
 *
 * Transcript (FR-118): one line per row — "row N: pass" or
 * "row N: FAIL <col>=<actual> ..." naming each failing output column and
 * the actual value observed (0/1/U/Z) — then a summary line
 * "passed R of T rows". Returns the number of failing rows (so main()
 * exits 0 iff everything passed). */
int rt_run_vectors(void);

/* ------------------------------------------------------------------ *
 *  Free-running mode (--cycles N, FR-117a)
 * ------------------------------------------------------------------ */

/* rt_run_free runs the design free — no vector rows, standard input
 * untouched. The clock and power-on-reset built-ins are time-driven,
 * exactly as in the editor's interactive run: each clock emits its FR-084
 * square wave at its own effective period (low the first half of each
 * period, so the first rising edge lands half a period in), and each
 * reset asserts R=1,/R=0 while simulated time < cycles × clockPeriod
 * (FR-071b; clockPeriod is the lone clock's period when the design has
 * exactly one clock generator, else the 100 ns default). Switches drive
 * their baked levels; ports are undriven.
 *
 * The run advances exactly `cycles` × clockPeriod unit steps — no settle
 * loop — then writes one line per observable column (FR-118 set: the
 * input columns, then the output columns, in column order) to standard
 * output as "LABEL=v", v the four-state value 0/1/U/Z. Bus conflicts
 * report to standard error as ever (FR-108). */
void rt_run_free(long cycles);

/* ==================================================================== *
 *  The gen_* interface — implemented by the generated <design>.c
 * ==================================================================== */

/* --- Nets and labels --- */

/* Number of nets. Net indices run 0..gen_net_count-1. */
extern const int gen_net_count;

/* Driver/probe name strings, "refdes.pin" (e.g. "U3.Q0"), indexed by the
 * `label` argument of rt_contrib and by the built-in tables below. Used
 * verbatim in bus-conflict reports (FR-108/FR-082). */
extern const char *const gen_labels[];
extern const int gen_label_count;

/* Upper bound on the contributions deposited in any one step (the total
 * driver count: every output-capable pin, built-in driver, and input
 * column). Sizes the runtime's contribution buffer. */
extern const int gen_max_contribs;

/* --- Lowered design logic --- */

/* gen_init resets all generated state to power-up: registers to U (FR-079)
 * and switches to their baked levels. Memory contents are reset by the
 * runtime (rt reset of the gen_mems store, FR-114/FR-116a), not here.
 * Called once before any step. */
void gen_init(void);

/* gen_latch updates registered state from the previous step's net values
 * (`curr`): .R register latching on each relevant clock's 0→1 edge
 * (FR-079/FR-079a). Called by rt_step before any contribution is
 * evaluated, so latching sees the pre-step values, exactly like the slow
 * simulator. Empty in a purely combinational design. (Memory write ports
 * are latched by the runtime from gen_mems, FR-114d, not here.) */
void gen_latch(const rt_val *curr);

/* gen_drive computes every generated strong driver from `curr` and
 * deposits it via rt_contrib: each GALasm output (plain, .T-gated, or
 * registered, FR-079) and each behavior-less type's U-driving output
 * (FR-080). The runtime's own built-in drivers, including memory data
 * pins (below, from gen_mems), are not gen_drive's concern. */
void gen_drive(const rt_val *curr);

/* --- Built-in instances (behaviors live in runtime.c, FR-116a) --- */

/* Weak pull-up/pull-down (FR-069/FR-070/FR-083). value is RT_1 or RT_0. */
typedef struct {
  int net;
  rt_val value;
  int label;
} rt_pull;
extern const rt_pull gen_pulls[];
extern const int gen_pull_count;

/* Input switch (FR-071c/FR-087a): a strong driver of `level`, its
 * persisted editor state baked at generate time. Mutable: a bound vector
 * input column overwrites `level` row by row. */
typedef struct {
  int net;
  rt_val level;
  int label;
} rt_switch;
extern rt_switch gen_switches[];
extern const int gen_switch_count;

/* Clock generator (FR-071/FR-071a). In vector mode the runner scripts
 * `level` (0/1/C semantics, FR-115e); in free-running mode (FR-117a)
 * `level` is ignored and the runtime computes the FR-084 square wave
 * from `period_ns` and simulated time. gen_clock_count > 0 is the
 * sequential/combinational split (FR-086). Mutable: the runner sets
 * `level`. A clock whose label contains '/' sits inside a flattened
 * sub-design (FR-116 hierarchy): no vector column can script it, so
 * vector mode refuses such a design at startup (exit 2) while
 * free-running mode drives it normally. */
typedef struct {
  int net;
  rt_val level;
  int period_ns;
  int label;
} rt_clock;
extern rt_clock gen_clocks[];
extern const int gen_clock_count;

/* Power-on reset (FR-071b): drives R and /R, asserted for `cycles`
 * scripted clock pulses in the vector preamble (FR-115e). Mutable: the
 * runner flips `released`. */
typedef struct {
  int r_net;  /* R  (active high), or -1 when unwired */
  int rn_net; /* /R (active low), or -1 when unwired */
  int cycles;
  int released; /* 0 = asserting reset, 1 = released */
  int r_label;
  int rn_label;
} rt_reset;
extern rt_reset gen_resets[];
extern const int gen_reset_count;

/* Memory device (RAM/ROM, FR-114/FR-114d; behavior in runtime.c, memory.js
 * core). The runtime owns a per-instance mutable store (2^abits × width
 * rt_val, RAM power-up U, ROM seeded from its loaded contents) plus
 * WE/-edge state; this table is the const wiring. `addr`/`data`/
 * `data_label` point at abits- and width-long net-index / label arrays
 * baked in the generated file; a control net is -1 when unwired (reads U).
 * `we` is -1 for a ROM.
 *
 * A ROM's contents are NOT baked: the runtime reads them at startup
 * (FR-117b), so a content file can change without regenerating. Per ROM,
 * the source is a `--rom REFDES=FILE` command-line override when given,
 * else `rom_file` — the content-file path recorded in the device's mem
 * block (FR-114f), tried as recorded and then by basename in the current
 * working directory. Format by extension per FR-114e (`.bin` raw bytes,
 * `.hex` whitespace-separated hex byte tokens), packed little-endian
 * ceil(width/8) bytes per word. Any load failure reports to stderr and
 * exits 2. `refdes` names the instance for --rom matching and messages.
 *
 * A persistent RAM (FR-114g/FR-117c) bakes `ram_file` (its save-file path)
 * and `ram_load` (the load-on-start flag). When `ram_load` is set the runtime
 * seeds the RAM from `ram_file` at startup like a ROM, but non-fatally: a
 * missing/malformed file reports to stderr and the RAM powers up all-U. On
 * normal termination of either batch mode the runtime writes the RAM's full
 * contents back to `ram_file` (U written as 0). There is no --ram override. */
typedef enum { RT_MEM_ROM = 0, RT_MEM_RAM = 1 } rt_mem_kind;
typedef struct {
  int kind;   /* rt_mem_kind */
  int abits;  /* address lines A0(LSB)..A(abits-1) */
  int width;  /* data lines D0..D(width-1) */
  const int *addr;       /* abits net indices */
  const int *data;       /* width net indices */
  const int *data_label; /* width gen_labels indices (conflict reports) */
  int ce;                /* CE/ net index (active low), or -1 */
  int oe;                /* OE/ net index (active low), or -1 */
  int we;                /* WE/ net index (active low, RAM), or -1 */
  const char *refdes;    /* instance refdes (--rom matching, messages) */
  const char *rom_file;  /* recorded content-file path (ROM), or NULL */
  const char *ram_file;  /* persistent save-file path (RAM), or NULL (FR-117c) */
  int ram_load;          /* seed RAM from ram_file at startup (FR-117c) */
} rt_mem;
extern const rt_mem gen_mems[];
extern const int gen_mem_count;

/* gen_latch_count > 0 marks a transparent latch present (FR-079d). A clock-less
 * latch design is still STATEFUL: the vector runner runs its rows in order on
 * persistent state (FR-115e), like a clocked design — the C analogue of
 * vectors.js isStateful (§6.16). */
extern const int gen_latch_count;

/* --- Vector columns (FR-117) --- */

/* Input column kinds: what the row symbol drives. */
typedef enum {
  RT_COL_SWITCH, /* ref indexes gen_switches; symbol sets .level */
  RT_COL_CLOCK,  /* ref indexes gen_clocks; symbols 0/1/C (FR-115e) */
  RT_COL_PORT,   /* ref is a net index; symbol strong-drives the net
                  * (the external-stimulus force of FR-115f) */
} rt_col_kind;

typedef struct {
  rt_col_kind kind;
  int ref;
  const char *name;   /* column display label, for the transcript */
  const char *refdes; /* column identity: instance ref (FR-115a, --columns) */
  const char *pin;    /* column identity: pin name (FR-115a, --columns) */
  int label;          /* gen_labels index for the stimulus driver */
} rt_incol;
extern const rt_incol gen_incols[];
extern const int gen_incol_count;

/* Output column: read `net` after settling and score it (FR-115c). */
typedef struct {
  int net;
  const char *name;
  const char *refdes; /* column identity: instance ref (FR-115a, --columns) */
  const char *pin;    /* column identity: pin name (FR-115a, --columns) */
} rt_outcol;
extern const rt_outcol gen_outcols[];
extern const int gen_outcol_count;

#endif /* RETROSIM_RUNTIME_H */
