#!/bin/sh
# Clean-rebuild and run the editor from the sim/ folder.
# Usage: ./test [extra retrosim flags]
set -e

cd "$(dirname "$0")"

rm -f ./retrosim
(cd srv && go build -o ../retrosim ./cmd/retrosim)

exec ./retrosim --web-dir=./web --components-dir=./srv/components "$@"
