/* 2-bit-adder — generated by retrosim (fast engine, specs §3.23).
 * Compile with the runtime pair delivered alongside this file:
 *   cc <this file> runtime.c
 * Do not edit: regenerate from the design instead. */

#include "runtime.h"

const int gen_net_count = 17;

const char *const gen_labels[] = {
  "A-11.OUT",
  "A-12.OUT",
  "A-13.OUT",
  "A-14.OUT",
  "A-15.OUT",
  "X1/A-17.OUT",
  "X2/A-17.OUT",
  "X1/U1A.1Y",
  "X1/U1B.2Y",
  "X1/U1C.3Y",
  "X1/U1D.4Y",
  "X1/U2A.1Y",
  "X1/U2B.2Y",
  "X1/U2C.3Y",
  "X1/U2D.4Y",
  "X1/U3A.1Y",
  "X1/U3B.2Y",
  "X1/U3C.3Y",
  "X1/U3D.4Y",
  "X2/U1A.1Y",
  "X2/U1B.2Y",
  "X2/U1C.3Y",
  "X2/U1D.4Y",
  "X2/U2A.1Y",
  "X2/U2B.2Y",
  "X2/U2C.3Y",
  "X2/U2D.4Y",
  "X2/U3A.1Y",
  "X2/U3B.2Y",
  "X2/U3C.3Y",
  "X2/U3D.4Y",
};
const int gen_label_count = 31;
const int gen_max_contribs = 31;

/* --- built-in instances (behaviors live in runtime.c, FR-116a) --- */
const rt_pull gen_pulls[] = {
  { 12, RT_0, 5 },
  { 16, RT_0, 6 },
};
const int gen_pull_count = 2;

rt_switch gen_switches[] = {
  { 5, RT_1, 0 }, /* A-11 */
  { 4, RT_1, 1 }, /* A-12 */
  { 3, RT_1, 2 }, /* A-13 */
  { 6, RT_1, 3 }, /* A-14 */
  { 7, RT_0, 4 }, /* A-15 */
};
const int gen_switch_count = 5;

rt_clock gen_clocks[] = { { -1, RT_0, 0, 0 } }; /* none */
const int gen_clock_count = 0;

rt_reset gen_resets[] = { { -1, -1, 0, 0, 0, 0 } }; /* none */
const int gen_reset_count = 0;

const rt_mem gen_mems[] = { { 0, 0, 0, 0, 0, 0, -1, -1, -1, 0, 0 } }; /* none */
const int gen_mem_count = 0;

/* --- vector columns (FR-117; column order is the row format) --- */
const rt_incol gen_incols[] = {
  { RT_COL_SWITCH, 0, "inA0", "A-11", "OUT", 0 },
  { RT_COL_SWITCH, 1, "inB0", "A-12", "OUT", 0 },
  { RT_COL_SWITCH, 2, "inA1", "A-13", "OUT", 0 },
  { RT_COL_SWITCH, 3, "inB1", "A-14", "OUT", 0 },
  { RT_COL_SWITCH, 4, "A-15", "A-15", "OUT", 0 },
};
const int gen_incol_count = 5;

const rt_outcol gen_outcols[] = {
  { 0, "bit0out", "A-5", "IN" },
  { 1, "bit1out", "A-6", "IN" },
  { 2, "carryout", "A-7", "IN" },
  { 0, "bit0out", "A-8", "P" },
  { 1, "bit1out", "A-9", "P" },
  { 2, "carryout", "A-10", "P" },
};
const int gen_outcol_count = 6;

/* --- registered state (FR-079/FR-079a .R outputs) --- */
/* --- power-up state (FR-116a; reapplied per combinational row) --- */
void gen_init(void) {
  gen_switches[0].level = RT_1; /* A-11 baked state */
  gen_switches[1].level = RT_1; /* A-12 baked state */
  gen_switches[2].level = RT_1; /* A-13 baked state */
  gen_switches[3].level = RT_1; /* A-14 baked state */
  gen_switches[4].level = RT_0; /* A-15 baked state */
}

/* --- registered latch: .R outputs (FR-079/FR-079a, sim.js updateRegisters) --- */
void gen_latch(const rt_val *curr) {
  (void)curr;
}

/* --- strong drivers, one fragment per instance (FR-081) --- */
void gen_drive(const rt_val *curr) {
  (void)curr;
  /* X1/U1A, X1/U1B, X1/U1C, X1/U1D: type-7486 */
  { /* X1/U1A.1Y */
    rt_val v;
    v = rt_or(rt_and(rt_buf(curr[5]) /* 1A */, rt_not(curr[4]) /* /1B */), rt_and(rt_not(curr[5]) /* /1A */, rt_buf(curr[4]) /* 1B */));
    rt_contrib(8, v, 0, 7);
  }
  { /* X1/U1B.2Y */
    rt_val v;
    v = rt_or(rt_and(rt_buf(curr[8]) /* 2A */, rt_not(curr[7]) /* /2B */), rt_and(rt_not(curr[8]) /* /2A */, rt_buf(curr[7]) /* 2B */));
    rt_contrib(0, v, 0, 8);
  }
  { /* X1/U1C.3Y */
    rt_val v;
    v = rt_or(rt_and(rt_buf(curr[12]) /* 3A */, rt_not(curr[12]) /* /3B */), rt_and(rt_not(curr[12]) /* /3A */, rt_buf(curr[12]) /* 3B */));
    rt_contrib(-1, v, 0, 9);
  }
  { /* X1/U1D.4Y */
    rt_val v;
    v = rt_or(rt_and(rt_buf(curr[12]) /* 4A */, rt_not(curr[12]) /* /4B */), rt_and(rt_not(curr[12]) /* /4A */, rt_buf(curr[12]) /* 4B */));
    rt_contrib(-1, v, 0, 10);
  }
  /* X1/U2A, X1/U2B, X1/U2C, X1/U2D: type-7408 */
  { /* X1/U2A.1Y */
    rt_val v;
    v = rt_and(rt_buf(curr[7]) /* 1A */, rt_buf(curr[8]) /* 1B */);
    rt_contrib(9, v, 0, 11);
  }
  { /* X1/U2B.2Y */
    rt_val v;
    v = rt_and(rt_buf(curr[5]) /* 2A */, rt_buf(curr[4]) /* 2B */);
    rt_contrib(10, v, 0, 12);
  }
  { /* X1/U2C.3Y */
    rt_val v;
    v = rt_and(rt_buf(curr[12]) /* 3A */, rt_buf(curr[12]) /* 3B */);
    rt_contrib(-1, v, 0, 13);
  }
  { /* X1/U2D.4Y */
    rt_val v;
    v = rt_and(rt_buf(curr[12]) /* 4A */, rt_buf(curr[12]) /* 4B */);
    rt_contrib(-1, v, 0, 14);
  }
  /* X1/U3A, X1/U3B, X1/U3C, X1/U3D: type-7432 */
  { /* X1/U3A.1Y */
    rt_val v;
    v = rt_or(rt_buf(curr[9]) /* 1A */, rt_buf(curr[10]) /* 1B */);
    rt_contrib(11, v, 0, 15);
  }
  { /* X1/U3B.2Y */
    rt_val v;
    v = rt_or(rt_buf(curr[12]) /* 2A */, rt_buf(curr[12]) /* 2B */);
    rt_contrib(-1, v, 0, 16);
  }
  { /* X1/U3C.3Y */
    rt_val v;
    v = rt_or(rt_buf(curr[12]) /* 3A */, rt_buf(curr[12]) /* 3B */);
    rt_contrib(-1, v, 0, 17);
  }
  { /* X1/U3D.4Y */
    rt_val v;
    v = rt_or(rt_buf(curr[12]) /* 4A */, rt_buf(curr[12]) /* 4B */);
    rt_contrib(-1, v, 0, 18);
  }
  /* X2/U1A, X2/U1B, X2/U1C, X2/U1D: type-7486 */
  { /* X2/U1A.1Y */
    rt_val v;
    v = rt_or(rt_and(rt_buf(curr[3]) /* 1A */, rt_not(curr[6]) /* /1B */), rt_and(rt_not(curr[3]) /* /1A */, rt_buf(curr[6]) /* 1B */));
    rt_contrib(13, v, 0, 19);
  }
  { /* X2/U1B.2Y */
    rt_val v;
    v = rt_or(rt_and(rt_buf(curr[13]) /* 2A */, rt_not(curr[11]) /* /2B */), rt_and(rt_not(curr[13]) /* /2A */, rt_buf(curr[11]) /* 2B */));
    rt_contrib(1, v, 0, 20);
  }
  { /* X2/U1C.3Y */
    rt_val v;
    v = rt_or(rt_and(rt_buf(curr[16]) /* 3A */, rt_not(curr[16]) /* /3B */), rt_and(rt_not(curr[16]) /* /3A */, rt_buf(curr[16]) /* 3B */));
    rt_contrib(-1, v, 0, 21);
  }
  { /* X2/U1D.4Y */
    rt_val v;
    v = rt_or(rt_and(rt_buf(curr[16]) /* 4A */, rt_not(curr[16]) /* /4B */), rt_and(rt_not(curr[16]) /* /4A */, rt_buf(curr[16]) /* 4B */));
    rt_contrib(-1, v, 0, 22);
  }
  /* X2/U2A, X2/U2B, X2/U2C, X2/U2D: type-7408 */
  { /* X2/U2A.1Y */
    rt_val v;
    v = rt_and(rt_buf(curr[11]) /* 1A */, rt_buf(curr[13]) /* 1B */);
    rt_contrib(14, v, 0, 23);
  }
  { /* X2/U2B.2Y */
    rt_val v;
    v = rt_and(rt_buf(curr[3]) /* 2A */, rt_buf(curr[6]) /* 2B */);
    rt_contrib(15, v, 0, 24);
  }
  { /* X2/U2C.3Y */
    rt_val v;
    v = rt_and(rt_buf(curr[16]) /* 3A */, rt_buf(curr[16]) /* 3B */);
    rt_contrib(-1, v, 0, 25);
  }
  { /* X2/U2D.4Y */
    rt_val v;
    v = rt_and(rt_buf(curr[16]) /* 4A */, rt_buf(curr[16]) /* 4B */);
    rt_contrib(-1, v, 0, 26);
  }
  /* X2/U3A, X2/U3B, X2/U3C, X2/U3D: type-7432 */
  { /* X2/U3A.1Y */
    rt_val v;
    v = rt_or(rt_buf(curr[14]) /* 1A */, rt_buf(curr[15]) /* 1B */);
    rt_contrib(2, v, 0, 27);
  }
  { /* X2/U3B.2Y */
    rt_val v;
    v = rt_or(rt_buf(curr[16]) /* 2A */, rt_buf(curr[16]) /* 2B */);
    rt_contrib(-1, v, 0, 28);
  }
  { /* X2/U3C.3Y */
    rt_val v;
    v = rt_or(rt_buf(curr[16]) /* 3A */, rt_buf(curr[16]) /* 3B */);
    rt_contrib(-1, v, 0, 29);
  }
  { /* X2/U3D.4Y */
    rt_val v;
    v = rt_or(rt_buf(curr[16]) /* 4A */, rt_buf(curr[16]) /* 4B */);
    rt_contrib(-1, v, 0, 30);
  }
}
