/* counter — generated by retrosim (fast engine, specs §3.23).
 * Compile with the runtime pair delivered alongside this file:
 *   cc <this file> runtime.c
 * Do not edit: regenerate from the design instead. */

#include "runtime.h"

const int gen_net_count = 9;

const char *const gen_labels[] = {
  "U1.QA",
  "U1.QB",
  "U1.QC",
  "U1.QD",
  "U1.RCO",
  "A-1.OUT",
  "A-2.OUT",
  "A-3.R",
  "A-3./R",
  "A-4.OUT",
};
const int gen_label_count = 10;
const int gen_max_contribs = 10;

/* --- built-in instances (behaviors live in runtime.c, FR-116a) --- */
const rt_pull gen_pulls[] = {
  { 1, RT_0, 6 },
  { 3, RT_1, 9 },
};
const int gen_pull_count = 2;

rt_switch gen_switches[] = { { -1, RT_0, 0 } }; /* none */
const int gen_switch_count = 0;

rt_clock gen_clocks[] = {
  { 0, RT_0, 100, 5 }, /* A-1 */
};
const int gen_clock_count = 1;

rt_reset gen_resets[] = {
  { -1, 2, 3, 0, 7, 8 }, /* A-3 */
};
const int gen_reset_count = 1;

const rt_mem gen_mems[] = { { 0, 0, 0, 0, 0, 0, -1, -1, -1, 0, 0 } }; /* none */
const int gen_mem_count = 0;

/* --- vector columns (FR-117; column order is the row format) --- */
const rt_incol gen_incols[] = {
  { RT_COL_CLOCK, 0, "A-1", "A-1", "OUT", 0 },
};
const int gen_incol_count = 1;

const rt_outcol gen_outcols[] = {
  { 4, "A-5", "A-5", "IN" },
  { 5, "A-6", "A-6", "IN" },
  { 6, "A-7", "A-7", "IN" },
  { 7, "A-8", "A-8", "IN" },
  { 8, "A-9", "A-9", "IN" },
  { 0, "A-10", "A-10", "IN" },
  { 2, "A-11", "A-11", "IN" },
};
const int gen_outcol_count = 7;

/* --- registered state (FR-079/FR-079a .R outputs) --- */
static rt_val reg_U1[4];
static rt_val prevClk_U1;

/* --- power-up state (FR-116a; reapplied per combinational row) --- */
void gen_init(void) {
  gen_clocks[0].level = RT_0;
  gen_resets[0].released = 0;
  reg_U1[0] = RT_U; /* power-up U (FR-079) */
  reg_U1[1] = RT_U; /* power-up U (FR-079) */
  reg_U1[2] = RT_U; /* power-up U (FR-079) */
  reg_U1[3] = RT_U; /* power-up U (FR-079) */
  prevClk_U1 = RT_U;
}

/* --- registered latch: .R outputs (FR-079/FR-079a, sim.js updateRegisters) --- */
void gen_latch(const rt_val *curr) {
  {
    rt_val gclk = curr[0]; /* global clock: pin */
    int grose = (prevClk_U1 == RT_0 && gclk == RT_1);
    if (grose) {
      reg_U1[0] = rt_or(rt_or(rt_or(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_not(curr[3]) /* /LOAD */), rt_buf(curr[1]) /* A */), rt_and(rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_buf(curr[3]) /* ENP */), rt_buf(curr[3]) /* ENT */), rt_not(curr[4]) /* /QA */)), rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_not(curr[3]) /* /ENP */), rt_buf(curr[4]) /* QA */)), rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_not(curr[3]) /* /ENT */), rt_buf(curr[4]) /* QA */));
      reg_U1[1] = rt_or(rt_or(rt_or(rt_or(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_not(curr[3]) /* /LOAD */), rt_buf(curr[1]) /* B */), rt_and(rt_and(rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_buf(curr[3]) /* ENP */), rt_buf(curr[3]) /* ENT */), rt_buf(curr[4]) /* QA */), rt_not(curr[5]) /* /QB */)), rt_and(rt_and(rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_buf(curr[3]) /* ENP */), rt_buf(curr[3]) /* ENT */), rt_not(curr[4]) /* /QA */), rt_buf(curr[5]) /* QB */)), rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_not(curr[3]) /* /ENP */), rt_buf(curr[5]) /* QB */)), rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_not(curr[3]) /* /ENT */), rt_buf(curr[5]) /* QB */));
      reg_U1[2] = rt_or(rt_or(rt_or(rt_or(rt_or(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_not(curr[3]) /* /LOAD */), rt_buf(curr[1]) /* C */), rt_and(rt_and(rt_and(rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_buf(curr[3]) /* ENP */), rt_buf(curr[3]) /* ENT */), rt_buf(curr[4]) /* QA */), rt_buf(curr[5]) /* QB */), rt_not(curr[6]) /* /QC */)), rt_and(rt_and(rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_buf(curr[3]) /* ENP */), rt_buf(curr[3]) /* ENT */), rt_not(curr[4]) /* /QA */), rt_buf(curr[6]) /* QC */)), rt_and(rt_and(rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_buf(curr[3]) /* ENP */), rt_buf(curr[3]) /* ENT */), rt_not(curr[5]) /* /QB */), rt_buf(curr[6]) /* QC */)), rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_not(curr[3]) /* /ENP */), rt_buf(curr[6]) /* QC */)), rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_not(curr[3]) /* /ENT */), rt_buf(curr[6]) /* QC */));
      reg_U1[3] = rt_or(rt_or(rt_or(rt_or(rt_or(rt_or(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_not(curr[3]) /* /LOAD */), rt_buf(curr[1]) /* D */), rt_and(rt_and(rt_and(rt_and(rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_buf(curr[3]) /* ENP */), rt_buf(curr[3]) /* ENT */), rt_buf(curr[4]) /* QA */), rt_buf(curr[5]) /* QB */), rt_buf(curr[6]) /* QC */), rt_not(curr[7]) /* /QD */)), rt_and(rt_and(rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_buf(curr[3]) /* ENP */), rt_buf(curr[3]) /* ENT */), rt_not(curr[4]) /* /QA */), rt_buf(curr[7]) /* QD */)), rt_and(rt_and(rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_buf(curr[3]) /* ENP */), rt_buf(curr[3]) /* ENT */), rt_not(curr[5]) /* /QB */), rt_buf(curr[7]) /* QD */)), rt_and(rt_and(rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_buf(curr[3]) /* ENP */), rt_buf(curr[3]) /* ENT */), rt_not(curr[6]) /* /QC */), rt_buf(curr[7]) /* QD */)), rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_not(curr[3]) /* /ENP */), rt_buf(curr[7]) /* QD */)), rt_and(rt_and(rt_and(rt_buf(curr[2]) /* CLR */, rt_buf(curr[3]) /* LOAD */), rt_not(curr[3]) /* /ENT */), rt_buf(curr[7]) /* QD */));
    }
    prevClk_U1 = gclk;
  }
}

/* --- strong drivers, one fragment per instance (FR-081) --- */
void gen_drive(const rt_val *curr) {
  (void)curr;
  /* U1: type-74163 */
  { /* U1.QA */
    rt_val v;
    v = reg_U1[0]; /* latched */
    rt_contrib(4, v, 0, 0);
  }
  { /* U1.QB */
    rt_val v;
    v = reg_U1[1]; /* latched */
    rt_contrib(5, v, 0, 1);
  }
  { /* U1.QC */
    rt_val v;
    v = reg_U1[2]; /* latched */
    rt_contrib(6, v, 0, 2);
  }
  { /* U1.QD */
    rt_val v;
    v = reg_U1[3]; /* latched */
    rt_contrib(7, v, 0, 3);
  }
  { /* U1.RCO */
    rt_val v;
    v = rt_and(rt_and(rt_and(rt_and(rt_buf(curr[3]) /* ENT */, rt_buf(curr[4]) /* QA */), rt_buf(curr[5]) /* QB */), rt_buf(curr[6]) /* QC */), rt_buf(curr[7]) /* QD */);
    rt_contrib(8, v, 0, 4);
  }
}
